export const trafficData = [{
    name: '不限',
    value: 0
}, {
    name: '北京南苑机场',
    value: 1
}, {
    name: '首都机场T3航站楼',
    value: 2
}, {
    name: '首都机场T2航站楼',
    value: 3
}, {
    name: '首都机场T1航站楼',
    value: 4
}, {
    name: '北京站',
    value: 5
}, {
    name: '北京西站',
    value: 6
}, {
    name: '北京北站',
    value: 7
}, {
    name: '北京南站',
    value: 8
}, {
    name: '东直门长途汽车站',
    value: 9
}, {
    name: '天桥长途汽车站',
    value: 10
}, {
    name: '德胜门长途汽车站',
    value: 11
}, {
    name: '丽泽桥长途汽车站',
    value: 12
}, {
    name: '西直门汽车客运站',
    value: 13
}, {
    name: '莲花池长途汽车站',
    value: 14
}, {
    name: '北京北郊长途汽车站',
    value: 15
}, {
    name: '四惠长途汽车站',
    value: 16
}, {
    name: '永定门长途汽车站',
    value: 17
}, {
    name: '八王坟长途汽车站',
    value: 18
}, {
    name: '北京南站长途汽车站',
    value: 19
}, {
    name: '木樨园长途汽车站',
    value: 20
}, {
    name: '六里桥长途客运站',
    value: 21
}, {
    name: '新发地长途客运站',
    value: 22
}, {
    name: '赵公口长途客运站',
    value: 23
}];
export const localData = [{
    name: '不限',
    value: 0
}, {
    name: '首都机场',
    value: '1'
}, {
    name: '东直门商圈',
    value: '2'
}, {
    name: '王府井商圈',
    value: '3'
}, {
    name: '前门商圈',
    value: '4'
}, {
    name: '三里屯，工体',
    value: '5'
}, {
    name: '后海，什刹海',
    value: '6'
}];
export const distanceData = [{
    name: '全城',
    value: 0
}, {
    name: '500m',
    value: 500
}, {
    name: '1km',
    value: 1
}, {
    name: '2km',
    value: 2
}, {
    name: '3km',
    value: 3
}, {
    name: '5km',
    value: 5
}];
export const reginData = [{
    name: '不限',
    value: 0,
    itemType: 'RADIO'
}, {
    name: '东城区',
    value: 1
}, {
    name: '西城区',
    value: 2
}, {
    name: '朝阳区',
    value: 3
}, {
    name: '丰台区',
    value: 4
}, {
    name: '石景山区',
    value: 5
}, {
    name: '海淀区',
    value: 6
}, {
    name: '门头沟区',
    value: 7
}, {
    name: '房山区',
    value: 8
}, {
    name: '通州区',
    value: 9
}, {
    name: '顺义区',
    value: 10
}, {
    name: '昌平区',
    value: 11
}, {
    name: '大兴区',
    value: 12
}, {
    name: '怀柔区',
    value: 13
}, {
    name: '平谷区',
    value: 14
}, {
    name: '密云县',
    value: 15
}, {
    name: '延庆县',
    value: 16
}];
export const toturistAttractionData = {
    urban: [{
        name: '不限',
        value: 0
    }, {
        name: '天安门',
        value: 1
    }, {
        name: '南锣鼓巷',
        value: 2
    }, {
        name: '鸟巢',
        value: 3
    }, {
        name: '故宫',
        value: 4
    }, {
        name: '天坛',
        value: 5
    }, {
        name: '北京动物园',
        value: 6
    }, {
        name: '颐和园',
        value: 7
    }, {
        name: '欢乐谷',
        value: 8
    }, {
        name: '雍和宫',
        value: 9
    }, {
        name: '鼓楼',
        value: 10
    }, {
        name: '什刹海',
        value: 11
    }, {
        name: '798艺术区',
        value: 12
    }, {
        name: '水立方',
        value: 13
    }, {
        name: '北海公园',
        value: 14
    }, {
        name: '朝阳公园',
        value: 15
    }, {
        name: '圆明园',
        value: 16
    }, {
        name: '奥林匹克公园',
        value: 17
    }, {
        name: '中国科技馆',
        value: 18
    }, {
        name: '国家大剧院',
        value: 19
    }, {
        name: '军事博物馆',
        value: 20
    }, {
        name: '世界公园',
        value: 21
    }, {
        name: '大观园',
        value: 22
    }, {
        name: '恭王府',
        value: 23
    }, {
        name: '国家博物馆',
        value: 24
    }],
    suburbs: [{
        name: '就是不限',
        value: 0
    }, {
        name: '天安门',
        value: 1
    }, {
        name: '南锣鼓巷',
        value: 2
    }, {
        name: '鸟巢',
        value: 3
    }, {
        name: '故宫',
        value: 4
    }, {
        name: '天坛',
        value: 5
    }, {
        name: '北京动物园',
        value: 6
    }, {
        name: '颐和园',
        value: 7
    }, {
        name: '欢乐谷',
        value: 8
    }, {
        name: '雍和宫',
        value: 9
    }, {
        name: '鼓楼',
        value: 10
    }, {
        name: '什刹海',
        value: 11
    }, {
        name: '798艺术区',
        value: 12
    }, {
        name: '水立方',
        value: 13
    }, {
        name: '北海公园',
        value: 14
    }, {
        name: '朝阳公园',
        value: 15
    }, {
        name: '圆明园',
        value: 16
    }, {
        name: '奥林匹克公园',
        value: 17
    }, {
        name: '中国科技馆',
        value: 18
    }, {
        name: '国家大剧院',
        value: 19
    }, {
        name: '军事博物馆',
        value: 20
    }, {
        name: '世界公园',
        value: 21
    }, {
        name: '大观园',
        value: 22
    }, {
        name: '恭王府',
        value: 23
    }, {
        name: '国家博物馆',
        value: 24
    }]
};
export const subWayData = {
    1: [{
        name: '不限',
        itemType: 'RADIO',
        value: 0
    }, {
        name: '四惠东地铁站',
        value: 1
    }, {
        name: '四惠地铁站',
        value: 2
    }, {
        name: '大望路地铁站',
        value: 3
    }, {
        name: '国贸地铁站',
        value: 4
    }, {
        name: '永安里地铁站',
        value: 5
    }, {
        name: '建国门地铁站',
        value: 6
    }, {
        name: '东单地铁站',
        value: 7
    }, {
        name: '王府井地铁站',
        value: 8
    }, {
        name: '天安门东地铁站',
        value: 9
    }, {
        name: '天安门西地铁站',
        value: 10
    }, {
        name: '西单地铁站',
        value: 11
    }, {
        name: '复兴门地铁站',
        value: 12
    }, {
        name: '南礼士路地铁站',
        value: 13
    }, {
        name: '木樨地地铁站',
        value: 14
    }, {
        name: '军事博物馆地铁站',
        value: 15
    }, {
        name: '公主坟地铁站',
        value: 16
    }, {
        name: '万寿路地铁站',
        value: 17
    }, {
        name: '五棵松地铁站',
        value: 18
    }, {
        name: '玉泉路地铁站',
        value: 19
    }, {
        name: '八宝山地铁站',
        value: 20
    }, {
        name: '八角游乐园地铁站',
        value: 21
    }, {
        name: '古城地铁站',
        value: 22
    }, {
        name: '苹果园地铁站',
        value: 23
    }],
    2: [{
        name: '东直门地铁站',
        value: 1
    }, {
        name: '东四十条地铁站',
        value: 2
    }, {
        name: '朝阳门地铁站',
        value: 3
    }, {
        name: '建国门地铁站',
        value: 4
    }, {
        name: '北京站地铁站',
        value: 5
    }, {
        name: '崇文门地铁站',
        value: 6
    }, {
        name: '前门地铁站',
        value: 7
    }, {
        name: '和平门地铁站',
        value: 8
    }, {
        name: '宣武门地铁站',
        value: 9
    }, {
        name: '长椿街地铁站',
        value: 10
    }, {
        name: '复兴门地铁站',
        value: 11
    }, {
        name: '阜成门地铁站',
        value: 12
    }, {
        name: '车公庄地铁站',
        value: 13
    }, {
        name: '西直门地铁站',
        value: 14
    }, {
        name: '积水潭地铁站',
        value: 15
    }, {
        name: '鼓楼大街地铁站',
        value: 16
    }, {
        name: '安定门地铁站',
        value: 17
    }, {
        name: '雍和宫地铁站',
        value: 18
    }]
};

export const hot = [
	{
		"name": "迈阿密",
		value: 0
	}, {
		"name": "墨西哥",
		value: 1
	}, {
		"name": "西雅图",
		value: 2
	}, {
		"name": "奥兰多",
		value: 3
	}, {
		"name": "洛杉矶",
		value: 4
	}, {
		"name": "大峡谷",
		value: 5
	}, {
		"name": "圣地亚哥",
		value: 6
	}, {
		"name": "旧金山",
		value: 7
	}, {
		"name": "多伦多",
		value: 8
	}, {
		"name": "纽约",
		value: 9
	}, {
		"name": "波士顿",
		value: 10
	}, {
		"name": "华盛顿",
		value: 11
	}, {
		"name": "墨尔本",
		value: 12
	}, {
		"name": "悉尼",
		value: 13
	}, {
		"name": "皇后镇",
		value: 14
	}, {
		"name": "基督城",
		value: 15
	}, {
		"name": "罗托鲁瓦",
		value: 16
	}, {
		"name": "英国",
		value: 17
	}, {
		"name": "北欧",
		value: 18
	}, {
		"name": "俄罗斯",
		value: 19
	}, {
		"name": "西班牙",
		value: 20
	}
]

export const american = {
	canada: [
		{
			name: "渥太华",
			value: 1
		}, {
			"tour_city_id": "124",
			"code": "TRT",
			"name": "多伦多",
			value: 2
		}, {
			"tour_city_id": "693",
			"code": "WHI",
			"name": "惠斯勒",
			value: 3
		}, {
			"tour_city_id": "138",
			"code": "QB",
			"name": "魁北克",
			value: 4
		}, {
			"tour_city_id": "136",
			"code": "MTL",
			"name": "蒙特利尔",
			value: 5
		}, {
			"tour_city_id": "21175",
			"code": "NOL",
			"name": "尼亚加拉滨湖小镇",
			value: 6
		}, {
			"tour_city_id": "20544",
			"code": "NFON",
			"name": "尼亚加拉瀑布市",
			value: 7
		}, {
			"tour_city_id": "32263",
			"code": "SQU",
			"name": "斯阔米什",
			value: 8
		}, {
			"tour_city_id": "30247",
			"code": "TSAW",
			"name": "Tsawwassen",
			value: 9
		}, {
			"tour_city_id": "788",
			"code": "VCV",
			"name": "温哥华",
			value: 10
		}, {
			"tour_city_id": "604",
			"code": "VTR",
			"name": "维多利亚",
			value: 11
		}
	],
	american:[
		{
			"tour_city_id": "23719",
			"code": "PSDNA",
			"name": "帕萨迪纳",
			"value": "0"
		}, {
			"tour_city_id": "22678",
			"code": "WOO",
			"name": "伍德伯里",
			"value": "1"
		}, {
			"tour_city_id": "35799",
			"code": "ILMRD",
			"name": "伊斯拉莫拉达",
			"value": "2"
		}, {
			"tour_city_id": "41184",
			"code": "GA",
			"name": "盖文斯顿(Galveston)",
			"value": "3"
		}, {
			"tour_city_id": "257",
			"code": "AN",
			"name": "阿纳海姆",
			"value": "4"
		}, {
			"tour_city_id": "378",
			"code": "OLD",
			"name": "奥兰多",
			"value": "5"
		}, {
			"tour_city_id": "23095",
			"code": "ESCO",
			"name": "爱丽丝镇",
			"value": "6"
		}, {
			"tour_city_id": "25450",
			"code": "OATMN",
			"name": "奥塔曼鬼镇",
			"value": "7"
		}, {
			"tour_city_id": "20712",
			"code": "ALB",
			"name": "奥尔巴尼",
			"value": "8"
		}, {
			"tour_city_id": "576",
			"code": "ANCH",
			"name": "安克雷奇",
			"value": "9"
		}, {
			"tour_city_id": "71",
			"code": "BS",
			"name": "波士顿",
			"value": "10"
		}, {
			"tour_city_id": "87",
			"code": "BIH",
			"name": "巴尔的摩内港",
			"value": "11"
		}, {
			"tour_city_id": "27442",
			"code": "BCNV",
			"name": "Boulder City (Nev.)",
			"value": "12"
		}, {
			"tour_city_id": "10087",
			"code": "PTL",
			"name": "波特兰",
			"value": "13"
		}, {
			"tour_city_id": "21967",
			"code": "LHT",
			"name": "捕鲸镇",
			"value": "14"
		}, {
			"tour_city_id": "29380",
			"code": "BLDR",
			"name": "博尔德",
			"value": "15"
		}, {
			"tour_city_id": "341",
			"code": "BRK",
			"name": "布鲁克林",
			"value": "16"
		}, {
			"tour_city_id": "22399",
			"code": "LOB",
			"name": "长滩",
			"value": "17"
		}, {
			"tour_city_id": "330",
			"code": "MMA",
			"name": "大都会艺术博物馆",
			"value": "18"
		}, {
			"tour_city_id": "20405",
			"code": "DN",
			"name": "迪纳利",
			"value": "19"
		}, {
			"tour_city_id": "208",
			"code": "DWMK",
			"name": "迪士尼-魔法王国",
			"value": "20"
		}, {
			"tour_city_id": "104",
			"code": "ESB",
			"name": "帝国大厦",
			"value": "21"
		}, {
			"tour_city_id": "24214",
			"code": "DLLS",
			"name": "达拉斯",
			"value": "22"
		}, {
			"tour_city_id": "20008",
			"code": "GC",
			"name": "大峡谷",
			"value": "23"
		}, {
			"tour_city_id": "21610",
			"code": "GIL",
			"name": "大岛",
			"value": "24"
		}, {
			"tour_city_id": "35251",
			"code": "EBW",
			"name": "东不伦瑞克",
			"value": "25"
		}, {
			"tour_city_id": "27114",
			"code": "FLT",
			"name": "菲尔顿小镇",
			"value": "26"
		}, {
			"tour_city_id": "588",
			"code": "FBS",
			"name": "费尔班克斯",
			"value": "27"
		}, {
			"tour_city_id": "219",
			"code": "PX",
			"name": "凤凰城",
			"value": "28"
		}, {
			"tour_city_id": "67",
			"code": "PHL",
			"name": "费城",
			"value": "29"
		}, {
			"tour_city_id": "65",
			"code": "DC",
			"name": "华盛顿",
			"value": "30"
		}, {
			"tour_city_id": "38127",
			"code": "WC",
			"name": "核桃溪",
			"value": "31"
		}, {
			"tour_city_id": "654",
			"code": "HOWO",
			"name": "好莱坞",
			"value": "32"
		}, {
			"tour_city_id": "29157",
			"code": "IR",
			"name": "尔湾",
			"value": "33"
		}, {
			"tour_city_id": "21913",
			"code": "GIL",
			"name": "吉尔罗伊",
			"value": "34"
		}, {
			"tour_city_id": "542",
			"code": "BA",
			"name": "旧金山湾区",
			"value": "35"
		}, {
			"tour_city_id": "20907",
			"code": "KM",
			"name": "金曼",
			"value": "36"
		}, {
			"tour_city_id": "25459",
			"code": "OGUQT",
			"name": "金库镇(缅因州)",
			"value": "37"
		}, {
			"tour_city_id": "2",
			"code": "SFO",
			"name": "旧金山",
			"value": "38"
		}, {
			"tour_city_id": "25447",
			"code": "CHLRD",
			"name": "矿镇，Chloride",
			"value": "39"
		}, {
			"tour_city_id": "21028",
			"code": "COR",
			"name": "康宁",
			"value": "40"
		}, {
			"tour_city_id": "741",
			"code": "QC",
			"name": "昆西",
			"value": "41"
		}, {
			"tour_city_id": "688",
			"code": "KAU",
			"name": "可爱岛",
			"value": "42"
		}, {
			"tour_city_id": "677",
			"code": "KK",
			"name": "科纳",
			"value": "43"
		}, {
			"tour_city_id": "1",
			"code": "LA",
			"name": "洛杉矶",
			"value": "44"
		}, {
			"tour_city_id": "826",
			"code": "FLD",
			"name": "罗德岱堡",
			"value": "45"
		}, {
			"tour_city_id": "676",
			"code": "WV",
			"name": "伦瑟姆村",
			"value": "46"
		}, {
			"tour_city_id": "3",
			"code": "LV",
			"name": "拉斯维加斯",
			"value": "47"
		}, {
			"tour_city_id": "20796",
			"code": "CMB",
			"name": "马萨诸塞州剑桥",
			"value": "48"
		}, {
			"tour_city_id": "20904",
			"code": "AT",
			"name": "美国大西洋赌城",
			"value": "49"
		}, {
			"tour_city_id": "20826",
			"code": "LC",
			"name": "美国兰卡斯特",
			"value": "50"
		}, {
			"tour_city_id": "10011",
			"code": "MIA",
			"name": "迈阿密",
			"value": "51"
		}, {
			"tour_city_id": "23494",
			"code": "MAUI",
			"name": "茂宜",
			"value": "52"
		}, {
			"tour_city_id": "23497",
			"code": "SBM",
			"name": "迈阿密南海滩",
			"value": "53"
		}, {
			"tour_city_id": "265",
			"code": "MM",
			"name": "曼哈顿中城区",
			"value": "54"
		}, {
			"tour_city_id": "23317",
			"code": "MLBU",
			"name": "马里布",
			"value": "55"
		}, {
			"tour_city_id": "673",
			"code": "IOM",
			"name": "茂宜岛",
			"value": "56"
		}, {
			"tour_city_id": "23439",
			"code": "NFNY",
			"name": "尼亚加拉瀑布城",
			"value": "57"
		}, {
			"tour_city_id": "66",
			"code": "NY",
			"name": "纽约",
			"value": "58"
		}, {
			"tour_city_id": "69",
			"code": "NH",
			"name": "纽黑文",
			"value": "59"
		}, {
			"tour_city_id": "23389",
			"code": "OAHU",
			"name": "欧胡岛",
			"value": "60"
		}, {
			"tour_city_id": "30105",
			"code": "PD",
			"name": "棕榈沙漠",
			"value": "61"
		}, {
			"tour_city_id": "21226",
			"code": "PR",
			"name": "普罗旺斯镇",
			"value": "62"
		}, {
			"tour_city_id": "21382",
			"code": "PLM",
			"name": "普利茅斯",
			"value": "63"
		}, {
			"tour_city_id": "841",
			"code": "PR",
			"name": "普罗维登斯",
			"value": "64"
		}, {
			"tour_city_id": "40155",
			"code": "Pontiac",
			"name": "庞蒂亚克",
			"value": "65"
		}, {
			"tour_city_id": "43",
			"code": "PG",
			"name": "佩吉市",
			"value": "66"
		}, {
			"tour_city_id": "38124",
			"code": "CH",
			"name": "钱德勒",
			"value": "67"
		}, {
			"tour_city_id": "44",
			"code": "FS",
			"name": "旗杆市",
			"value": "68"
		}, {
			"tour_city_id": "394",
			"code": "CWT",
			"name": "清水市",
			"value": "69"
		}, {
			"tour_city_id": "31",
			"code": "SDN",
			"name": "塞多纳",
			"value": "70"
		}, {
			"tour_city_id": "25444",
			"code": "SPRNFLD",
			"name": "斯普林菲尔德(马萨诸塞州)",
			"value": "71"
		}, {
			"tour_city_id": "64",
			"code": "SJ",
			"name": "圣何塞",
			"value": "72"
		}, {
			"tour_city_id": "25",
			"code": "SCMT",
			"name": "萨克拉门托",
			"value": "73"
		}, {
			"tour_city_id": "709",
			"code": "SA",
			"name": "圣奥古斯丁",
			"value": "74"
		}, {
			"tour_city_id": "23",
			"code": "SD",
			"name": "圣地亚哥",
			"value": "75"
		}, {
			"tour_city_id": "844",
			"code": "SCT",
			"name": "斯科茨代尔",
			"value": "76"
		}, {
			"tour_city_id": "21475",
			"code": "CGS",
			"name": "珊瑚阁",
			"value": "77"
		}, {
			"tour_city_id": "10141",
			"code": "SA",
			"name": "圣安东尼奥",
			"value": "78"
		}, {
			"tour_city_id": "12",
			"code": "SM",
			"name": "圣塔莫尼卡",
			"value": "79"
		}, {
			"tour_city_id": "22768",
			"code": "SAC",
			"name": "圣克鲁斯",
			"value": "80"
		}, {
			"tour_city_id": "22",
			"code": "SB",
			"name": "圣塔芭芭拉",
			"value": "81"
		}, {
			"tour_city_id": "818",
			"code": "STP",
			"name": "圣彼得堡",
			"value": "82"
		}, {
			"tour_city_id": "162",
			"code": "HNLL",
			"name": "檀香山",
			"value": "83"
		}, {
			"tour_city_id": "10069",
			"code": "TP",
			"name": "坦帕",
			"value": "84"
		}, {
			"tour_city_id": "20601",
			"code": "TUS",
			"name": "图森",
			"value": "85"
		}, {
			"tour_city_id": "29091",
			"code": "TM",
			"name": "蒂梅丘拉",
			"value": "86"
		}, {
			"tour_city_id": "174",
			"code": "WKK",
			"name": "威基基海滩",
			"value": "87"
		}, {
			"tour_city_id": "70",
			"code": "NP",
			"name": "新港",
			"value": "88"
		}, {
			"tour_city_id": "595",
			"code": "ST",
			"name": "西雅图",
			"value": "89"
		}, {
			"tour_city_id": "742",
			"code": "NO",
			"name": "新奥尔良",
			"value": "90"
		}, {
			"tour_city_id": "22993",
			"code": "WPB",
			"name": "西棕榈滩市",
			"value": "91"
		}, {
			"tour_city_id": "21937",
			"code": "HEG",
			"name": "希尔兹堡",
			"value": "92"
		}, {
			"tour_city_id": "702",
			"code": "KW",
			"name": "西礁岛",
			"value": "93"
		}, {
			"tour_city_id": "541",
			"code": "GCWR",
			"name": "西峡谷",
			"value": "94"
		}, {
			"tour_city_id": "675",
			"code": "HI",
			"name": "希洛",
			"value": "95"
		}, {
			"tour_city_id": "802",
			"code": "HST",
			"name": "休斯顿",
			"value": "96"
		}, {
			"tour_city_id": "711",
			"code": "IDO",
			"name": "印第奥",
			"value": "97"
		}, {
			"tour_city_id": "743",
			"code": "ALT",
			"name": "亚特兰大",
			"value": "98"
		}, {
			"tour_city_id": "41085",
			"code": "MEIGUO",
			"name": "中国国内各大机场\\/市内 ",
			"value": "99"
		}, {
			"tour_city_id": "845",
			"code": "PS",
			"name": "棕榈泉",
			"value": "100"
		}, {
			"tour_city_id": "10015",
			"code": "CHI",
			"name": "芝加哥",
			"value": "101"
		}, {
			"tour_city_id": "25054",
			"code": "PLMBCH",
			"name": "棕榈滩市",
			"value": "102"
		}
	],
	Mexico: [
		{
			"tour_city_id": "415",
			"code": "TN",
			"name": "蒂华纳",
			"value": "D"
		}, {
			"tour_city_id": "48",
			"code": "ESNA",
			"name": "恩塞纳达",
			"value": "E"
		}, {
			"tour_city_id": "724",
			"code": "CC",
			"name": "坎昆",
			"value": "K"
		}, {
			"tour_city_id": "49",
			"code": "RSRT",
			"name": "罗萨里托",
			"value": "L"
		}, {
			"tour_city_id": "32413",
			"code": "PUNU",
			"name": "龙虾湾",
			"value": "P"
		}
	]
}

export const Austrilia = {
	Austrilia: [
		{
			"tour_city_id": "27063",
			"code": "PR",
			"name": "珀斯",
			"value": "#"
		}, {
			"tour_city_id": "822",
			"code": "AS",
			"name": "爱丽丝泉",
			"value": "A"
		}, {
			"tour_city_id": "823",
			"code": "ADLD",
			"name": "阿德莱德",
			"value": "A1"
		}, {
			"tour_city_id": "21781",
			"code": "BYBA",
			"name": "拜伦湾",
			"value": "B"
		}, {
			"tour_city_id": "821",
			"code": "BRSB",
			"name": "布里斯班",
			"value": "B1"
		}, {
			"tour_city_id": "10134",
			"code": "PODO",
			"name": "道格拉斯港",
			"value": "D"
		}, {
			"tour_city_id": "20940",
			"code": "HBT",
			"name": "霍巴特",
			"value": "H"
		}, {
			"tour_city_id": "20949",
			"code": "HMTI",
			"name": "汉密尔顿岛",
			"value": "H1"
		}, {
			"tour_city_id": "24634",
			"code": "HAIS",
			"name": "汉密尔顿岛,澳洲",
			"value": "H2"
		}, {
			"tour_city_id": "861",
			"code": "GC",
			"name": "黄金海岸",
			"value": "H3"
		}, {
			"tour_city_id": "20356",
			"code": "CB",
			"name": "堪培拉",
			"value": "K"
		}, {
			"tour_city_id": "20360",
			"code": "CS",
			"name": "凯恩斯",
			"value": "K1"
		}, {
			"tour_city_id": "26077",
			"code": "LNCTN",
			"name": "朗塞斯顿",
			"value": "L"
		}, {
			"tour_city_id": "820",
			"code": "MLB",
			"name": "墨尔本",
			"value": "M"
		}, {
			"tour_city_id": "30343",
			"code": "MRTI",
			"name": "摩顿岛",
			"value": "M1"
		}, {
			"tour_city_id": "20916",
			"code": "TW",
			"name": "圣灵群岛",
			"value": "S"
		}, {
			"tour_city_id": "20922",
			"code": "TS",
			"name": "塔斯马尼亚",
			"value": "T"
		}, {
			"tour_city_id": "20925",
			"code": "ULURU",
			"name": "乌鲁鲁",
			"value": "W"
		}, {
			"tour_city_id": "819",
			"code": "SYD",
			"name": "悉尼",
			"value": "X"
		}, {
			"tour_city_id": "30891",
			"code": "CP",
			"name": "中央海岸",
			"value": "Z"
		}	
	],
	Newzl:[
		{
			"tour_city_id": "32325",
			"code": "MT",
			"name": "库克山",
			"value": "#"
		}, {
			"tour_city_id": "36229",
			"code": "GOY",
			"name": "格林诺奇",
			"value": "#1"
		}, {
			"tour_city_id": "37060",
			"code": "MBG",
			"name": "马尔堡",
			"value": "#2"
		}, {
			"tour_city_id": "25101",
			"code": "OAMA",
			"name": "奥玛鲁",
			"value": "A"
		}, {
			"tour_city_id": "609",
			"code": "AL",
			"name": "奥克兰",
			"value": "A1"
		}, {
			"tour_city_id": "30300",
			"code": "DK",
			"name": "蒂卡普",
			"value": "D"
		}, {
			"tour_city_id": "618",
			"code": "TA",
			"name": "蒂阿瑙",
			"value": "D1"
		}, {
			"tour_city_id": "619",
			"code": "QS",
			"name": "皇后镇",
			"value": "H"
		}, {
			"tour_city_id": "30345",
			"code": "WT",
			"name": "怀托摩",
			"value": "H1"
		}, {
			"tour_city_id": "611",
			"code": "WL",
			"name": "惠灵顿",
			"value": "H2"
		}, {
			"tour_city_id": "614",
			"code": "CC",
			"name": "基督城",
			"value": "J"
		}, {
			"tour_city_id": "37821",
			"code": "KTT",
			"name": "凯特里特里",
			"value": "K"
		}, {
			"tour_city_id": "30276",
			"code": "KK",
			"name": "凯库拉",
			"value": "K1"
		}, {
			"tour_city_id": "610",
			"code": "R",
			"name": "罗托鲁瓦",
			"value": "L"
		}, {
			"tour_city_id": "25104",
			"code": "MATAM",
			"name": "玛塔玛塔",
			"value": "M"
		}, {
			"tour_city_id": "24345",
			"code": "MIS",
			"name": "米尔福德峡湾",
			"value": "M1"
		}, {
			"tour_city_id": "30396",
			"code": "PC",
			"name": "派希亚",
			"value": "P"
		}, {
			"tour_city_id": "24330",
			"code": "TAO",
			"name": "陶波",
			"value": "T"
		}, {
			"tour_city_id": "30102",
			"code": "LW",
			"name": "瓦纳卡湖",
			"value": "W"
		}, {
			"tour_city_id": "31602",
			"code": "WN",
			"name": "瓦纳卡",
			"value": "W1"
		}
	],
	French:[
		{
			"tour_city_id": "35580",
			"code": "BB",
			"name": "波拉波拉岛",
			"value": "B"
		}, {
			"tour_city_id": "35598",
			"code": "MI",
			"name": "茉莉亚岛",
			"value": "M"
		}, {
			"tour_city_id": "30243",
			"code": "PAP",
			"name": "帕皮提，波利尼西亚",
			"value": "P"
		}
	]
}

export const Europe = {
	Andorra: [
		{
			"tour_city_id": "26902",
			"code": "ALV",
			"name": "安道尔城",
			"value": "A"
		}
	],
	Austria: [
		{
			"tour_city_id": "641",
			"code": "SA",
			"name": "萨尔茨堡",
			"value": "S"
		}, {
			"tour_city_id": "640",
			"code": "VI",
			"name": "维也纳",
			"value": "W"
		}
	],
	Belgium: [
		{
			"tour_city_id": "642",
			"code": "BR",
			"name": "布鲁塞尔",
			"value": "B"
		}, {
			"tour_city_id": "24847",
			"code": "WTRLOO",
			"name": "滑铁卢",
			"value": "H"
		}
	],
	Swit: [
		{
			"tour_city_id": "643",
			"code": "LU",
			"name": "琉森",
			"value": "L"
		}, {
			"tour_city_id": "23796",
			"code": "SFF",
			"name": "沙夫豪森",
			"value": "S"
		}, {
			"tour_city_id": "662",
			"code": "ZUR",
			"name": "苏黎世",
			"value": "A"
		}
	],
	Czech: [
		{
			"tour_city_id": "25623",
			"code": "CB",
			"name": "布杰约维采",
			"value": "B"
		}, {
			"tour_city_id": "651",
			"code": "PR",
			"name": "布拉格",
			"value": "B1"
		}, {
			"tour_city_id": "25626",
			"code": "CK",
			"name": "克鲁姆洛夫",
			"value": "K"
		}, {
			"tour_city_id": "25620",
			"code": "KV",
			"name": "卡罗维发利",
			"value": "K1"
		}, {
			"tour_city_id": "23532",
			"code": "MALA",
			"name": "玛丽亚温泉市",
			"value": "M"
		}, {
			"tour_city_id": "25629",
			"code": "PZ",
			"name": "皮尔森",
			"value": "P"
		}
	],
	Germany: [
		{
			"tour_city_id": "25920",
			"code": "ES",
			"name": "埃森",
			"value": "A"
		}, {
			"tour_city_id": "660",
			"code": "BER",
			"name": "柏林",
			"value": "B"
		}, {
			"tour_city_id": "21349",
			"code": "BADEN",
			"name": "巴登巴登",
			"value": "B1"
		}, {
			"tour_city_id": "625",
			"code": "BN",
			"name": "波恩",
			"value": "B2"
		}, {
			"tour_city_id": "26361",
			"code": "DRES",
			"name": "德累斯顿",
			"value": "D"
		}, {
			"tour_city_id": "23553",
			"code": "DD",
			"name": "杜塞尔多夫",
			"value": "D1"
		}, {
			"tour_city_id": "623",
			"code": "FR",
			"name": "法兰克福",
			"value": "F"
		}, {
			"tour_city_id": "20362",
			"code": "HB",
			"name": "汉堡",
			"value": "H"
		}, {
			"tour_city_id": "24142",
			"code": "HDLBRG",
			"name": "海德堡",
			"value": "H1"
		}, {
			"tour_city_id": "30054",
			"code": "GUZ",
			"name": "金茨堡",
			"value": "J"
		}, {
			"tour_city_id": "627",
			"code": "KO",
			"name": "科布伦茨",
			"value": "K"
		}, {
			"tour_city_id": "20494",
			"code": "CO",
			"name": "科隆",
			"value": "K1"
		}, {
			"tour_city_id": "24097",
			"code": "rhine_river11",
			"name": "莱茵河",
			"value": "L"
		}, {
			"tour_city_id": "659",
			"code": "MUN",
			"name": "慕尼黑",
			"value": "M"
		}, {
			"tour_city_id": "23763",
			"code": "STG",
			"name": "斯图加特",
			"value": "S"
		}, {
			"tour_city_id": "626",
			"code": "TR",
			"name": "特里尔",
			"value": "T"
		}, {
			"tour_city_id": "27807",
			"code": "WD",
			"name": "威斯巴登",
			"value": "W"
		}
	],
	Denmark: [
		{
			"tour_city_id": "20513",
			"code": "CH",
			"name": "哥本哈根",
			"value": "G"
		}
	],
	England: [
		{
			"tour_city_id": "24405",
			"code":"AMES",
			"name": "埃姆斯伯里",
			"value": "A"
		}, {
			"tour_city_id": "21583",
			"code": "BAT",
			"name": "巴斯",
			"value": "B"
		}, {
			"tour_city_id": "20443",
			"code": "BH",
			"name": "伯明翰",
			"value": "B1"
		}, {
			"tour_city_id": "20484",
			"code": "CB",
			"name": "剑桥",
			"value": "J"
		}, {
			"tour_city_id": "24420",
			"code": "COT",
			"name": "科茨沃尔德",
			"value": "K"
		}, {
			"tour_city_id": "655",
			"code": "LON",
			"name": "伦敦",
			"value": "L"
		}, {
			"tour_city_id": "22381",
			"code": "LEE",
			"name": "利兹",
			"value": "L1"
		}, {
			"tour_city_id": "20444",
			"code": "MC",
			"name": "曼彻斯特",
			"value": "M"
		}, {
			"tour_city_id": "20483",
			"code": "OXF",
			"name": "牛津",
			"value": "N"
		}, {
			"tour_city_id": "20445",
			"code": "NOT",
			"name": "诺丁汉",
			"value": "N1"
		}, {
			"tour_city_id": "23416",
			"code": "CHSTR",
			"name": "切斯特",
			"value": "Q"
		}, {
			"tour_city_id": "23925",
			"code": "SUA",
			"name": "斯特拉斯福特",
			"value": "S"
		}, {
			"tour_city_id": "24178",
			"code": "YORK",
			"name": "英国约克",
			"value": "Y"
		}
	],
	Spain: [
		{
			"tour_city_id": "1016",
			"code": "ARJ",
			"name": "阿兰胡埃斯",
			"value": "A"
		}, {
			"tour_city_id": "1014",
			"code": "AV",
			"name": "阿维拉",
			"value": "A1"
		}, {
			"tour_city_id": "20506",
			"code": "BAR",
			"name": "巴塞罗那",
			"value": "B"
		}, {
			"tour_city_id": "23760",
			"code": "TLD",
			"name": "杜丽多",
			"value": "D"
		}, {
			"tour_city_id": "27001",
			"code": "FRGS",
			"name": "菲格拉斯",
			"value": "F"
		}, {
			"tour_city_id": "26944",
			"code": "GRNA",
			"name": "赫罗纳",
			"value": "H"
		}, {
			"tour_city_id": "27256",
			"code": "CDPLL",
			"name": "卡莱利亚德帕拉弗鲁赫尔",
			"value": "K"
		}, {
			"tour_city_id": "27307",
			"code": "LLFRC",
			"name": "拉弗朗克",
			"value": "L"
		}, {
			"tour_city_id": "658",
			"code": "MAD",
			"name": "马德里",
			"value": "M"
		}, {
			"tour_city_id": "672",
			"code": "MLG",
			"name": "马拉加",
			"value": "M1"
		}, {
			"tour_city_id": "27304",
			"code": "PALS",
			"name": "帕尔斯",
			"value": "P"
		}, {
			"tour_city_id": "28675",
			"code": "PDRZA",
			"name": "佩德拉萨",
			"value": "P1"
		}, {
			"tour_city_id": "1048",
			"code": "SMC",
			"name": "萨拉曼卡",
			"value": "S"
		}, {
			"tour_city_id": "1015",
			"code": "SGV",
			"name": "塞戈维亚",
			"value": "S1"
		}, {
			"tour_city_id": "1018",
			"code": "SVA",
			"name": " 塞维利亚",
			"value": "S2"
		}, {
			"tour_city_id": "1034",
			"code": "ZGZ",
			"name": "萨拉戈萨",
			"value": "S3"
		}, {
			"tour_city_id": "1012",
			"code": "TL",
			"name": "托莱多",
			"value": "T"
		}, {
			"tour_city_id": "812",
			"code": "VLC",
			"name": "瓦伦西亚",
			"value": "W"
		}, {
			"tour_city_id": "26530",
			"code": "STGES",
			"name": "锡切斯",
			"value": "X"
		}
	],
	French: [
		{
			"tour_city_id": "20308",
			"code": "AVI",
			"name": "阿维尼翁",
			"pinyin": "A"
		}, {
			"tour_city_id": "21385",
			"code": "ARLES",
			"name": "阿尔勒",
			"pinyin": "A1"
		}, {
			"tour_city_id": "622",
			"code": "PA",
			"name": "巴黎",
			"pinyin": "B"
		}, {
			"tour_city_id": "631",
			"code": "VSL",
			"name": "凡尔赛",
			"pinyin": "F"
		}, {
			"tour_city_id": "23716",
			"code": "GVNY",
			"name": "吉维尼小镇",
			"pinyin": "J"
		}, {
			"tour_city_id": "23818",
			"code": "CAEN",
			"name": "卡昂",
			"pinyin": "K"
		}, {
			"tour_city_id": "23934",
			"code": "LILLE",
			"name": "里尔",
			"pinyin": "L"
		}, {
			"tour_city_id": "632",
			"code": "RE",
			"name": "兰斯",
			"pinyin": "L2"
		}, {
			"tour_city_id": "35779",
			"code": "LOU",
			"name": "露德",
			"pinyin": "L3"
		}, {
			"tour_city_id": "23754",
			"code": "NM",
			"name": "尼姆",
			"pinyin": "N"
		}, {
			"tour_city_id": "633",
			"code": "NI",
			"name": "尼斯",
			"pinyin": "N1"
		}, {
			"tour_city_id": "26931",
			"code": "AP",
			"name": "普罗旺斯地区艾克斯",
			"pinyin": "P"
		}, {
			"tour_city_id": "23688",
			"code": "FDV",
			"name": "泉水小镇",
			"pinyin": "Q"
		}, {
			"tour_city_id": "25536",
			"code": "SM",
			"name": "圣马洛",
			"pinyin": "S"
		}
	]
}
